### ISSUE TITLE
phonegap plugin version update

### ISSUE THREAD

**Issue by deeeed** [chendong0120/meteor-heytz-jpush#1]
Have you tried to update the plugin to it's latest version ?
It seems installaing it directly has incompatibility with node bundled in meteor (I tried with meteor 1.5)

**Comment by chendong0120** [comment]
Hi ,
     I have updated to 1.5. You can try.

**Comment by chendong0120** [comment]
I'm usually lazy.  But you have problems can write "issues" , I will reply in time.
